[package]
name = "random_chess_puzzle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "2.5.1"
mongodb = "2.1.0"
futures = "0.3.19"
serde = "1.0.133"
serde_json = "1.0.74"